### ISSUE TITLE
Mark read a mail inside k9 app without syncing it with the server

### ISSUE THREAD

**Issue by justanidea** [k9mail/k9mail.github.io#101]
I have searched for it but it may not be possible for now. I would like to read my gmails from k9 without showing them as "read" on google servers. Do you think it would be possible? Or is there already a way to do it?

**Comment by BO41** [comment]
you are in the wrong repo for this. This is about the website k9mail.github.io .
The repo for the k9-app is here: https://github.com/k9mail/k-9 :slightly_smiling_face:

**Comment by BO41** [comment]
@justanidea did you try Settings -> Account Settings -> Reading mail -> Mark as read when opened ?
This sounds like a solution for your problem.

If you want the mails to be read, but the read status not to be synced, this would need a new issue indeed :wink:

**Comment by justanidea** [comment]
Thats what im talking about :) Not syncing the read statut 👍
Ty for the link
