### ISSUE TITLE
Related Apps => Links doesn't work

### ISSUE THREAD

**Issue by Maskulinum** [k9mail/k9mail.github.io#105]
Two Links under Related Apps ( https://k9mail.github.io/worksWithK9.html ) doesn't work:
- K-9 Mail DashClock Extension 
- K-9 Mail for SmartWatch

**Comment by cketti** [comment]
Thanks for the report. I've unpublished these apps because the platforms they target (DashClock Widget and Sony SmartWatch 2) aren't relevant anymore. We'll update the site to remove the links.
