### ISSUE TITLE
Breadcrumb links 404 due to trailing slash

### ISSUE THREAD

**Issue by 9x6** [k9mail/k9mail.github.io#117]
Following breadcrumb links end up on a 404 page due to trailing slashes in the URLs. For example: [documentation/security](https://k9mail.app/documentation/security) has a breadcrumb link 'documentation' back to [https://k9mail.app/documentation/](https://k9mail.app/documentation/) (404) instead of [https://k9mail.app/documentation](https://k9mail.app/documentation) (expected content). All breadcrumbs except for home seem to affected.
Possibly part of the fallout of this [issue](https://github.com/jekyll/jekyll/issues/4440).

**Comment by AnXh3L0** [comment]
Thanks for opening this issue, I'll make sure to fix this today.
