### ISSUE TITLE
No Backroundsync an Android10 and Samsung Galaxy S10E

### ISSUE THREAD

**Issue by zie26** [k9mail/k9mail.github.io#118]
This repository is only for issues relating to the website. If your issue relates to the app use the app's issue tracker: https://github.com/k9mail/k-9
Hi,
I have been using K-9 Mail since Android 4 and I am always very satisfied. Unfortunately, it no longer works properly on Android 10 on my Samsung Galaxy S10E.
No matter which settings I choose (permanent sync / background), as soon as the program has not been open for some time and is in the background, the synchronization no longer works. The settings for power saving, standby etc. are all disabled for K9. If you keep the program in the foreground without, he will check the emails immediately. Would like to continue using the program, is there a possibility or an update in the near future? I don't want to have to switch to a different program.
Please help ! Best regards, Dirk

**Comment by cketti** [comment]
This repository is only for issues relating to the website. If your issue relates to the app use the app's issue tracker: https://github.com/k9mail/k-9
