### ISSUE TITLE
Broken URLs in https://k9mail.app/documentation/settings/account.html

### ISSUE THREAD

**Issue by tjejojyj** [k9mail/k9mail.github.io#121]
On the page https://k9mail.app/documentation/settings/account.html there are two broken links in this section

Outgoing server
Please see the section **Configuring the outgoing server** on the page **Setting up an email account** for the available settings.

It appears they should both link to this page.
                https://k9mail.app/documentation/accounts/add.html

**Comment by s3b-** [comment]
Fixed with #130
