### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by philipwhiuk** [k9mail/k9mail.github.io#14]
I think @cketti has to do this. I don't have permission:

https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by cketti** [comment]
Done. But this broke the site because all resources are referenced via http URI.

**Comment by cketti** [comment]
The template is using `site.url`. Maybe updating the site to trigger a rebuild is enough to rectify this.

**Comment by philipwhiuk** [comment]
I looked at the documentation and you need to specify the URL in a YAML config file. Done and fixed.
