### ISSUE TITLE
Identities unuseable with OpenKeychain to encrypt messages.

### ISSUE THREAD

**Issue by seppwarum** [k9mail/k9mail.github.io#140]
Yes, identities make life a lot easier, but only if you don't use OpenKeychain to encrypt messages.
Each identity created represents an address and needs its own key in OpenKeychain
(Thunderbird allows it to give each identity its own key).
Please remember this, when enforcing identities!

_Originally posted by @seppwarum in https://github.com/k9mail/k-9/issue_comments/708576102_

**Comment by philipwhiuk** [comment]
Wrong repository - you commented in the right one. This is the website repo.
