### ISSUE TITLE
K9 not sending ....or copying into sent ...

### ISSUE THREAD

**Issue by mmmoshko** [k9mail/k9mail.github.io#152]
the new version of k9 mail does not send emails ... smtp server works ... it was working on the previous version ... it also does not copy into the sent folder.

The mail server logs do not show it connecting, the sending settings are correct.

Matee Moshkovits

**Comment by AnXh3L0** [comment]
Hello, this is the website repo, you will want to move this issue to our forum or the main k9 repo over at k9mail/k9

**Comment by alain-pouc** [comment]
Bonjour,

J'ai installé K9 MAIL sur mon PIXEL 6 PRO et je reçois les mails sans problème. Cependant, bien que je puisse envoyer des mails, ils n'apparaissent pas dans le dossier des messages envoyés. De plus, il y a de nombreux dossiers dans les paramètres dont je ne saisis pas l'utilité, alors je les ai configurés en automatique.

Je suis presque prêt à installer un autre logiciel car j'utilise Thunderbird sur mon PC, et cela me frustre.

Si quelqu'un a une solution, ce serait gentil de la partager.

Merci beaucoup d'avance.
