### ISSUE TITLE
Blog post should have date + 'posted by'

### ISSUE THREAD

**Issue by cketti** [k9mail/k9mail.github.io#22]
I'd like us to display the date of the post and the person who posted the entry on the page.

Something like

> Posted by [philipwhiuk](https://www.github.com/philipwhiuk) on November 5, 2016

in a small font right below the heading.

**Comment by philipwhiuk** [comment]
Fixed in https://github.com/k9mail/k9mail.github.io/commit/65f8d46d424070c3bb0095c155690d07f29dd53e
