### ISSUE TITLE
Unread message count - defining which folders to include.

### ISSUE THREAD

**Issue by mrpassey** [k9mail/k9mail.github.io#24]
Hi,

Firstly, great app keep up the good work.

Secondly, I'm struggling to understand how to define which folders are being monitored to calculate the unread message count. I have many folders which are viewable on my android but I don't want the unread message count to include all of them.

Please advise how to proceed.

Kind regards,

Dan

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
