### ISSUE TITLE
Add a team/contributors page

### ISSUE THREAD

**Issue by cketti** [k9mail/k9mail.github.io#26]
Add a list of team members (commit access to the repository) and [contributors](https://github.com/k9mail/k-9/graphs/contributors).

We should probably distinguish active and inactive members. 'Active' could be 'at least one commit in the past 12 months'.

Ideally we'd also include translators. Although I have no idea how easy it is to extract that information from Transifex.

Maybe also include most active people on the mailing list.

**Comment by philipwhiuk** [comment]
I've left off the mailing list members for now and not looked at Transifex.

**Comment by cketti** [comment]
Did you automate this? I'd love to have a script we just run once a month or so.

**Comment by philipwhiuk** [comment]
No :( I'll create an issue for automatically generating it... I guess it'll involve the GitHub API which I've not really looked into.
