### ISSUE TITLE
Tune website design

### ISSUE THREAD

**Issue by cketti** [k9mail/k9mail.github.io#42]
The content area feels too wide. The font size too small, especially on blog posts.

Maybe it's easier to look for a new template that also works on mobile instead of fixing the issues we find with the existing one.

**Comment by hendrikbl** [comment]
I started working on a redesign of the website [here](https://github.com/hendrikbl/k9mail.github.io/tree/bootstrap-material). While doing so I found that the structure of folders and files could be improved too. 

Some ideas I have include
- [ ] Nice/Welcoming hero area
- [x] Bootstrap Material (Bootstrap 4) as a base
- [ ] autocreate list of contributors from github (via githubpages gem)
- [ ] Add some screenshots
- [ ] some "eye candy" in general

I'll be happy to hear your thoughts and ideas :)

**Comment by AnXh3L0** [comment]
If this is still viable, I would like to help with redesigning the whole website from scratch using a modern look (if that's ok with you). I have been using K9 for years now so I think it's th e least I could do to give back.

**Comment by AnXh3L0** [comment]
Hello again, I have forked the repo and will be working on it these couple of days. Will also post some screenshots here and my ideas about the site.

**Comment by cketti** [comment]
Sorry, for the silence. Yes to all ideas from @hendrikbl. Help with the website would be really appreciated.

**Comment by AnXh3L0** [comment]
No worries @cketti. I began work today and this is a "draft" I'm sharing, as below.

![image](https://user-images.githubusercontent.com/25004151/74443420-6cb18400-4e73-11ea-8c7b-9b3cd35a1ff3.png)

I'd need your help on the content soon, and of course this is subject to changes.

**Comment by AnXh3L0** [comment]
@cketti @hendrikbl what do you think? I am going to push what I did in a few hours, almost done. I also followed some other issues in the repo and tried to fix and implement them. The docs need a lot of updates but they are good for a first launch, I have also added full text search.

![image](https://user-images.githubusercontent.com/25004151/74557408-664d0600-4f60-11ea-9ad8-b31e67a48204.png)

**Comment by AnXh3L0** [comment]
This is the current state and link where you can check it out: https://anxh3l0.github.io/k9mail.github.io/

**Comment by cketti** [comment]
@AnXh3L0: Looks great :+1:

A couple of questions/remarks:
* Can you make it so old links still work? Either redirect to the new URL or make sure the new site reuses the same URLs?
* I see you used the same green the beta version of the app currently uses as secondary color. It's the default of the AppCompat theme and something I want to change eventually. Would that be a change that could be easily done for your design as well?
* We currently don't really have a contact email address. We'll have to figure out something eventually. But for now please remove info@k9mail.app.
* I recently registered a Twitter account that could be added to the social column: https://twitter.com/k9mail_app

Unless someone can make a good argument on why we shouldn't go forward with this design, I'd like to go ahead and use it. It's certainly much better than what we have now. The only thing I'd like to fix before switching to the new design is having old links still work (especially ones to blog posts).

**Comment by hendrikbl** [comment]
@AnXh3L0 I agree with @cketti , looks great 👍🏻

**Comment by AnXh3L0** [comment]
@cketti thanks for the feedback. Below answers to your questions:

1. Yeah, I can make old links work, I just liked /docs more instead of /documentation, but that's it. I'll revert that to /documentation. The blog post links are the same in the current revision so no need for fixes there.
2. Yes, changing colors is as simple as changing a few variables in scss files. Please let me know or guide me to a template/color palette you'd like to use so I can implement it.
3. Yeah sure, I can remove the email address for now.
4. I'll add the Twitter link to the social column and the sidebar on mobile.

Let me know if you have any more questions/feedback. Cheers!

**Comment by AnXh3L0** [comment]
I reverted the /docs to /documentation and fixed inner links. Screenshots need to be updated but those belong to the docs themselves. Removed the email address for now and added the Twitter link in the social section.

**Comment by cketti** [comment]
@AnXh3L0: :heart:  Can you create a pull request?

**Comment by AnXh3L0** [comment]
Sure @cketti. Before I do that, any opinion on the color palette?

**Comment by cketti** [comment]
> Before I do that, any opinion on the color palette?

Not yet. But the beta app currently uses the green, so why not the website? If it's easy to change later, we can do so later.

I'll probably start work on cleaning up the app UI in early March. That will most likely also include colors.

**Comment by AnXh3L0** [comment]
Ok cool, creating a PR.
