### ISSUE TITLE
Create proper privacy policy

### ISSUE THREAD

**Issue by cketti** [k9mail/k9mail.github.io#44]
Because we use the Contacts permissions we need to have a privacy policy and link to it from the Play Store. I created a first version here: https://github.com/k9mail/k-9/wiki/Privacy-Policy
At some point it should probably move from the wiki to the website.

Any help is highly appreciated.

**Comment by philipwhiuk** [comment]
The permissions page should link to it.

**Comment by cketti** [comment]
https://k9mail.app/privacy-policy.html
