### ISSUE TITLE
GMail Trash is now a defunct Folder; Now called Bin

### ISSUE THREAD

**Issue by PreachJohn** [k9mail/k9mail.github.io#56]
I noticed I couldn't access 'Download 25 Trash' in K-9 anymore.
On my PC I went to rummage in GMail Trash. Empty!!! O, no!
Till I realized that 'Trash' was still in the Menu but 'Bin' had been added. And all my Trash is in there.
K-9, if I am correct, needs now to add a 'Bin' Folder to access what used to be called GMail Trash.

**Comment by philipwhiuk** [comment]
You can change the folder designated trash. Also, this is not a website issue.

**Comment by PreachJohn** [comment]
I think that you are missing the issue.
K-9 Trash does the same on my phone as it does on my PC. It now goes nowhere.
But Bin as I pointed out is the new Trash.
What I am saying is that K-9 has now no access on my phone to this new Bin Folder.
i found this out when I looked for something in Trash on my phone and could not access it. And there is no Bin option on my phone.
PreachJohn

**Comment by PreachJohn** [comment]
I think that you are missing the issue.
K-9 Trash does the same on my phone as it does on my PC. It now goes
nowhere.
But Bin as I pointed out is the new Trash.
What I am saying is that K-9 has now no access on my phone to this new Bin
Folder.
i found this out when I looked for something in Trash on my phone and could
not access it. And there is no Bin option on my phone.
JohnB

**Comment by philipwhiuk** [comment]
You can refresh the folder list and then change the Trash to point to 'Bin' instead of Trash / nowhere. 

See: https://k9mail.github.io/documentation/settings/account.html#spam-folder

Again, not a website issue in any case.
