### ISSUE TITLE
Lost ability to easily send email to addresses that are not stored in phone's (google account) contacts

### ISSUE THREAD

**Issue by liar666** [k9mail/k9mail.github.io#60]
Hi,

Some time ago I decided to use K9 because it was the only _actual_ email client, with configurable SMTP/IMAP servers, etc, and not one of those mostly-GUI apps that do not know how to manage anything else but the GMail account related to the Google account the phone is linked to.

I don't remember how, (was that because I had autocompletion based on received emails? or I managed to add email addresses to K9 without having them stored in my contacts? or did I find a way, like in ThB, to "automatically add outgoing email addresses to address book"?) but I was able to send email to addresses that are not stored in my contacts, without having to type them everytime, i.e. with working autocompletion.

Recently, I had to flush the cache of K9 mail. I reconfigured my account, but this feature has disappeared and I cannot find a configuration item in the menus (I read them all 10th of times) to enable something like that.

In the forums on the web I find only references to adding email addresses in the contacts of the phone.

How could I get back the most-wanted feature of autocompleting email addresses (either that I have already typed, or that are present in the sent/received emails)?

**Comment by philipwhiuk** [comment]
This is not a website bug. I believe it's https://github.com/k9mail/k-9/issues/2829
