### ISSUE TITLE
gestures not working

### ISSUE THREAD

**Issue by Rubylion** [k9mail/k9mail.github.io#72]
hey. I got k9mail on a samsung s7 equinox, with lineage os 14.1. I activated gestures, but it wont allow me to swipe between the mails.

**Comment by philipwhiuk** [comment]
Wrong project.

**Comment by Rubylion** [comment]
what you mean
isn't this the k9mail project?

**Comment by philipwhiuk** [comment]
This is the project for the website - you want https://github.com/k9mail/k-9
