### ISSUE TITLE
Notification panel doesn't stay open

### ISSUE THREAD

**Issue by fcpelletier** [k9mail/k9mail.github.io#77]
Android 7.1.1 on Samsung Note 8.  I have always had this issue with K9.  When I pull down the Notification panel, and then pull down my K9 emails, and then pull down each email to see my actions, and choose "Delete", I wish for the Notification panel to stay open, in a similar manner as when I delete all other notifications.  In that way, if I have 6 emails to delete (and I don't want to open the app), I don't have to repeatedly pull everything open for each deletion.

**Comment by philipwhiuk** [comment]
Wrong project - this is the GitHub project for the documentation website.
