### ISSUE TITLE
k9mail stopped working when connected to wifi network

### ISSUE THREAD

**Issue by TexasUser** [k9mail/k9mail.github.io#78]
Late yesterday, my phone suddenly stopped connecting to send or receive emails.  Get messages like "UnknownHostException: Host".  Have discovered that it works only when I disconnect from my home wifi.  As soon as I reconnect, it stops working.  Help!

**Comment by philipwhiuk** [comment]
Can you resolve your email server from your home WiFi?On 22 Feb 2018 13:47, TexasUser <notifications@github.com> wrote:Late yesterday, my phone suddenly stopped connecting to send or receive emails.  Get messages like "UnknownHostException: Host".  Have discovered that it works only when I disconnect from my home wifi.  As soon as I reconnect, it stops working.  Help!

**Comment by TexasUser** [comment]
Not a techie.  Don't understand "resolve your email server".  I can access email via wifi with my desktop computer, if that helps.

**Comment by TexasUser** [comment]
I have powered down phone and restarted a few times with no impact on the problem.

**Comment by TexasUser** [comment]
FYI, rebooted both wifi router and phone.  No change.  Works without wifi.  Doesn't work with.

**Comment by TexasUser** [comment]
It appears this is not a k9mail issue.  Wife's phone uses Motorola's native motomail app and it is now doing the same thing ... won't work with wifi, does without.
