### ISSUE TITLE
 command continuation aborted #2# no, authentication mechanism not supported, mate k9 plain failed

### ISSUE THREAD

**Issue by kikibelux** [k9mail/k9mail.github.io#80]
Hi, 
I would use an opensource software for read my mail on android and learn your app on Korben site.

I used Mymail and Aquamail for reading mailbox and I meet any issue
but when I use K9, an issue occur : 
Smtp setting is ok ( I can send mail )
but I can receive any mail : it's display :  
"command continuation aborted #2# no, authentication mechanism not supported, mate k9 plain failed"

How Can I resolve it ? 
(The server name is scarlet.be)

Thanks a lot

**Comment by philipwhiuk** [comment]
Wrong project. This is an exact duplicate of #2648 The `scarlet.be` server lies about what it supports. It lists AUTH=PLAIN despite actually only supporting LOGIN:
