### ISSUE TITLE
Create a Licence file

### ISSUE THREAD

**Issue by shashikanth171** [k9mail/k9mail.github.io#82]
Please add Licence file so that I can get to know if I could use content from the website.

**Comment by philipwhiuk** [comment]
@Valodim @cketti Are you guys happy with Apache 2.0 - the same as the app?

**Comment by cketti** [comment]
I vaguely remember having read traditional software licenses don't work well for documentation/text. How about [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)?

**Comment by prahaladbelavadi** [comment]
Do we have consensus on the license ? @cketti @philipwhiuk @Valodim 

If so, I can open a pull request with the appropriate license.

**Comment by philipwhiuk** [comment]
Yep

**Comment by prahaladbelavadi** [comment]
Hey I just realized this.

I presumed the consensus was on  CC BY 4.0 but on re-reading this again , I realized that I hadn't asked what the consensus was on. It was my mistake.

Are we using Apache 2.0  or CC 4.0 ? @cketti i @philipwhiuk  @Valodim 

This [pull request](https://github.com/prahaladbelavadi/k9mail.github.io/commit/f227cac3e5250dc4dcd2a325d1e4759f0c694422) has a CC4.0 but if the consensus was on Apache 2.0, then I can open another pull request with the same.

Reference:
- [Apache](https://www.apache.org/licenses/LICENSE-2.0)
- [cc4.0](https://creativecommons.org/licenses/by/4.0/)
- [PR](https://github.com/prahaladbelavadi/k9mail.github.io/commit/f227cac3e5250dc4dcd2a325d1e4759f0c694422)

**Comment by cketti** [comment]
We now have a LICENSE file.
https://github.com/k9mail/k9mail.github.io/blob/master/LICENSE
