### ISSUE TITLE
button answer & forward

### ISSUE THREAD

**Issue by guillaumens1** [k9mail/k9mail.github.io#85]
Hello,
I don't understand on my smartphone I see two buttons one to answer to an opened email and a second one to forward it. On my tab these buttons are not displayed. I searched in the settings and specially in the display settings and don't find such option. I found option to display the anti spam button and expect to find the same for the two other items, but it is not the case.
Can anyone help me ?
Thanks in advance
Guillaume

**Comment by philipwhiuk** [comment]
There's a "Send" option, either on the toolbar or overflow menu that provides Reply and Forward actions.

As this is not feedback about the website I'm closing this issue - for bugs, use the "k-9" repository, following the issue template. For support, use the mailing list.
