### ISSUE TITLE
Uses efficient cache policy on static assets

### ISSUE THREAD

**Issue by BO41** [k9mail/k9mail.github.io#88]
>A long cache lifetime can speed up repeat visits to your page. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/cache-policy)

URL | Cache TTL | Size (KB)
-- | -- | --
…css/bootstrap.css(k9mail.github.io) | 10 m | 22 KB
…img/k9icon.png(k9mail.github.io) | 10 m | 14 KB
…js/bootstrap.min.js(k9mail.github.io) | 10 m | 10 KB
…css/k9mail.css(k9mail.github.io) | 10 m | 1 KB

**Comment by philipwhiuk** [comment]
Not possible https://stackoverflow.com/questions/14798589/github-pages-http-headers

**Comment by BO41** [comment]
:disappointed: 
thanks for the explanation :)
